// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using TwitterSentimentML.Model;

namespace TwitterSentimentML.Model
{
    public class ConsumeModel
    {
        private readonly PredictionEngine<ModelInput, ModelOutput> _Engine;
        private MLContext _Context = new MLContext();

        public ConsumeModel()
        {
            // Load model & create prediction engine
            string modelPath = AppDomain.CurrentDomain.BaseDirectory + "MLModel.zip";
            ITransformer mlModel = _Context.Model.Load(modelPath, out var modelInputSchema);
            _Engine = _Context.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public ModelOutput Predict(ModelInput input)
        {
            // Use model to make prediction on input data
            ModelOutput result = _Engine.Predict(input);
            return result;
        }
    }
}
