// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TwitterSentimentML.Model
{
    public class ModelInput
    {
        [ColumnName("Wow... Loved this place."), LoadColumn(0)]
        public string TextToAnalyze { get; set; }


        [ColumnName("1"), LoadColumn(1)]
        public bool Col1 { get; set; }


    }
}
